# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sortvis < Formula
  desc ""
  homepage ""
  version "0.3.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hamao0820/sortvis/releases/download/v0.3.1/sortvis_Darwin_arm64.tar.gz"
      sha256 "a67292431802fa3d37b87156593ff265fcfd42a70102073cdf7406c59dc371f8"

      def install
        bin.install "sortvis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hamao0820/sortvis/releases/download/v0.3.1/sortvis_Darwin_x86_64.tar.gz"
      sha256 "55656f5904a05cf96de4e2b5a1aa198d33d425be35612e35c3c351fb9e3a86fe"

      def install
        bin.install "sortvis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hamao0820/sortvis/releases/download/v0.3.1/sortvis_Linux_arm64.tar.gz"
      sha256 "ff09cdd49297a52d09046d0b356fd7716ab077eca1d6c600fe2631c4b9f9a3f9"

      def install
        bin.install "sortvis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hamao0820/sortvis/releases/download/v0.3.1/sortvis_Linux_x86_64.tar.gz"
      sha256 "d4038ff8014415baf41c2c8e5bd55a8c77548a7feef9776857d3c8b31f10d118"

      def install
        bin.install "sortvis"
      end
    end
  end
end
