# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sortvis < Formula
  desc ""
  homepage ""
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hamao0820/sortvis/releases/download/v0.3.2/sortvis_Darwin_x86_64.tar.gz"
      sha256 "ddd84b1a0257139251396928c32d876b50ded98d4bf31d2bd1fc80f9ae84a3bb"

      def install
        bin.install "sortvis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hamao0820/sortvis/releases/download/v0.3.2/sortvis_Darwin_arm64.tar.gz"
      sha256 "95bc729a4a3301a4f198651f6c2b9c1defa8c8b24c9ca1c6299ca2c7f45f9f24"

      def install
        bin.install "sortvis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hamao0820/sortvis/releases/download/v0.3.2/sortvis_Linux_arm64.tar.gz"
      sha256 "5d5fb02e87ac97d1053ff9a1b776a3ee7a75a8c4ecd8d805c6d0d53fc9ab43f7"

      def install
        bin.install "sortvis"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hamao0820/sortvis/releases/download/v0.3.2/sortvis_Linux_x86_64.tar.gz"
      sha256 "1f874601b341ab3a1f5fe22baa6a2e81d3b2b0a20309e3929be3e473cf4b46a8"

      def install
        bin.install "sortvis"
      end
    end
  end
end
